### ISSUE TITLE
Please don't point your package to my tarball for Homebrew

### ISSUE THREAD

**Issue by dinkypumpkin** [android-808/get_iplayer-PKGBUILD#1]
Someone in the AUR comments for get_iplayer erroneously claimed that the upstream location for release tarballs changed - not true.  Please don't point your package to my tarball for Homebrew - revert to the original location.  Thanks.

**Comment by android-808** [comment]
Sorry for the inconvenience, I was just tracking the aur PKGBUILD.

Unfortunately I seem to have a configuration issue somewhere as I haven't been able to access upstream ftp server for ages, either via Firefox or wget (wget now fixed).  The only method to work was "ftp" via command line.  At first it was limited to ftp://ftp.infradead.org but now it seems to be affecting ftp.mozilla.org as well.

**Comment by dinkypumpkin** [comment]
Thanks.  As an alternative to the FTP archive, you could also use the GitHub releases, e.g., https://github.com/get-iplayer/get_iplayer/archive/v2.92.tar.gz.
